### PR TITLE
Feature/api auth : Refactoring methods + route for refresh sign key + token timelife

### PR DESCRIPTION
**Pull request by defgenx**
I updated the SQL scheme to have a life_time column in api_keys table (OAuth2 standard). It handle exceptions if the token is outdated when the user try to verify if he has access to the board. Checking the token lifetime will be helpful when the user will request the api after all the process.

I also made a little refactoring on the method which had a TODO.

### CODE REVIEW

**Comment by defgenx** [comment]
I wasn't sure of your process after submitting this pull (and as you can see I hesitate many times). But something is strange. 

Knowing that the Auth token request is the "exchange_key" in our code, after giving consent to the app,  everything should be on server side. The server should return the auth_key. With this auth_key we should exchange it to get the sign_key and the refresh_token.
Take a look at the attach image and tell me if the process is ok for you.

auth_code_flow

**Comment by galaxyAbstractor** [comment]
Hey, I'm preparing for bed soon but I will take a closer look sometime during the coming week, I'm not really good with charts :P.

Anyway, the current flow doesn't really follow any standard, although it might be inspired from one. What happens now is something like this:

A client wants access to a forum and asks the forum for an exchange key. The forum generates an exchange key and saves it to the database (with a time for expiry, although purging hasn't been implemented yet), and returns it to the client.

The client then takes the exchange key and sends the user to the forum together with the exchange key, and asks the user to authorize the client. When the user has done so, an authentication key and signing key is generated and saved together with the exchange key. Then the client can fetch the authentication key and signing key by exchanging the exchange key.

Lastly the temporary exchange key is removed, and the client can now authenticate requests, by signing the request + a serial with the signing key.

I guess it's similar to what the chart depicts but obviously lacks stuff like redirect uri, scopes and stuff.

There was discussions, both on the forum and in IRC, to implement OAuth2 instead. I would be happy if someone could help me with that though since I'm kinda hopeless in understanding OAuth2, I've tried a couple of times but never got far enough to actually implement something.

Also, from my understanding of OAuth2, we would need some kind of central repo of applications unless each developer wants to register their clients with each and every forum running phpBB, which is a reason why I didn't go with OAuth2 in the first place. But I can't see why both auth systems couldn't be used side-by-side and letting forum-admins select which (or both) systems to allow, and maybe grant different type of permissions based on the auth type.

**Comment by defgenx** [comment]
I suggested OAuth2 on the forum too.... But it was because I already have a OAuth2 server. Now that I understood what the community want (An API that works just by installing phpBB), I can say that it's not the good solution to use OAuth2 process.
The best way to do it is surely yours (even if you can make even more control and use a better hash algorithm for keys), it works pretty well in my opinion.

I'll help on this branch to add some features if you want.

**Comment by galaxyAbstractor** [comment]
Hey, I've did a fast review of the commits but I haven't tried anything yet since the pull request is closed, since I'm unsure if you intend to reopen/make a new one.

You seem to have removed the install folder and accidentally commited that. Also, seems like you removed the hashing of the actual request in my api client prototype test tool and at first I was unsure about why since it was hashed for a reason (to prevent tampering of the request over unsecure connections, but maybe that's just a non-issue). But maybe I just missed something since I just went trough it quickly over my break.

I'm gonna discuss the authentication with the rest of the team a bit, so I know how to continue.

**Comment by defgenx** [comment]
Hmmmm.... I did some modifications but actually it wasn't good because I thougth that we'll work with a OAuth server later ; so don't take this pull on board.

Ha, I didn't see that I commited the delete of the install folder, it's my mistake. For the client.php I made some tests and the hash never match what the API is waiting. You hash the path with parameters and the API only hash parameters.

Anyway, I'll delete my commits because the way they are now, it's useless. I'll rollback my branch to your HEAD. Sorry for this last "false" pull but I wasn't sure about what the team wanted.

Don't hesitate to tell me when you'll know how to continue the API.

**Pull request closed without merging**
